### PR TITLE
fix llama ZERO3 error in weight split

### PR DESCRIPTION
**Pull request by sywangyi**

### CODE REVIEW

**Comment by nelyahu** [comment]
@sywangyi thanks for bringing this up.
1. can you please explain what is the exact scenario? 
2. What happens if the cast is executed although the dtype is the same?
3. how to reproduce this?
4. is it a general bug in DeepSpeed or was observed only on HPU?

**Comment by sywangyi** [comment]
hi, @nelyahu 
this is my test env
Running Env
1)	Gaudi2 with 1.11 driver.
2)	Components version: (very important)
transformers            4.34.0
optimum-habana: commit id ca8ecde25b5508336173bcb92c0239683e39d0fc + https://github.com/huggingface/optimum-habana/pull/466
Deepspeed: https://github.com/HabanaAI/DeepSpeed/tree/1.11.0
3)	Test script:
https://github.com/huggingface/optimum-habana/blob/main/examples/language-modeling/run_clm.py
python ../gaudi_spawn.py \
    --world_size 8 --use_deepspeed run_clm.py \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --save_strategy no \
    --output_dir /tmp/test-clm-xl-1 \
    --gaudi_config_name Habana/gpt2 \
    --model_name_or_path huggyllama/llama-7b \
    --use_habana \
    --throughput_warmup_steps 3 \
    --deepspeed deepspeed.json \
    --overwrite_output_dir \
    --use_lazy_mode \
--torch_dtype bfloat16 \

      deepspeed.json
      {
                 "steps_per_print": 64,
                "train_batch_size": "auto",
                 "train_micro_batch_size_per_gpu": "auto",
                "gradient_accumulation_steps": "auto",
                "bf16": {
               "enabled": true
                },
                "gradient_clipping": 1.0,
                "zero_optimization": {
               "stage": 3,
               "overlap_comm": false,
               "reduce_scatter": false,
               "contiguous_gradients": false
                }
     }

without the PR
crash like
Traceback (most recent call last):
  File "run_clm.py", line 689, in <module>
    main()
  File "run_clm.py", line 466, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/auto_factory.py", line 565, in from_pretrained
    return model_class.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 3085, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 400, in wrapper
    f(module, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 400, in wrapper
    f(module, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 965, in __init__
    self.model = LlamaModel(config)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 400, in wrapper
    f(module, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 790, in __init__
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 790, in <listcomp>
    self.layers = nn.ModuleList([LlamaDecoderLayer(config) for _ in range(config.num_hidden_layers)])
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 400, in wrapper
    f(module, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 602, in __init__
    self.mlp = LlamaMLP(config)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 400, in wrapper
    f(module, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 224, in __init__
    self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 407, in wrapper
    self._post_init_method(module)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 861, in _post_init_method
    dist.broadcast(param, 0, self.get_dp_process_group())
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/comm/comm.py", line 219, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/usr/local/lib/python3.8/dist-packages/deepspeed/comm/torch.py", line 117, in broadcast
    return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1451, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 1566, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: [Rank:1] FATAL ERROR :: MODULE:PT_BRIDGE syn compile encountered : Graph compile failed. synStatus 26 [Generice failure].  compile time 2012594 ns
I think  https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L136C82-L136C82 cause the issue, since inv_freq  is float32.

**Comment by sywangyi** [comment]
and it should be HPU specific issue

**Comment by nelyahu** [comment]
Thanks @sywangyi for providing all the details.
According to the error 
`FATAL` ERROR :: MODULE:PT_BRIDGE syn compile encountered : Graph compile failed`
We can learn that the error arriving from the Synapse Graph-Compiler. 
Next steps:
1. We will check if this issue still reproduces on latest under development version (upcoming 1.13.0).
2. Check if the suggested change in this PR indeed fixes this (or work around this).
3. We will debug this issue to understand what should be the proper fix (it is very possible that lower level change is required).

**Comment by sywangyi** [comment]
yes, I also assume the lower level change is required, the WA in deepspeed is just to make the function work in 1.11.

**Comment by nelyahu** [comment]
@sywangyi  Hi, we were able to reproduce the same issue on v1.11.0 according to the above instructions.
The good news is that it cannot be reproduced on v1.12.0 Habana SW release.
We recommend to use v1.12.0 Release, as it is official available for customer use.
You can close this PR.

Thanks for bringing it up for our attention.

**Comment by sywangyi** [comment]
thanks, we will update our SW stack to v1.12.0 Habana SW release.

**Pull request closed without merging**
