### PR TITLE
add sharded loading for safetensors in AutoTP (#4854)

### PR DESCRIPTION
**Pull request by tjs-intel**
Adds support for sharded loading of Safetensors. Commit from upstream microsoft/DeepSpeed.

### CODE REVIEW

**Comment by tjs-intel** [comment]
Some context: this is required for the [TinyLlama](https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v1.0) model to function because it only stores checkpoints in the safetensors format.

**Comment by tjs-intel** [comment]
This also enables https://huggingface.co/NousResearch/Nous-Hermes-2-SOLAR-10.7B and https://huggingface.co/upstage/SOLAR-10.7B-Instruct-v1.0

**Comment by tjs-intel** [comment]
@nelyahu can you please tag the appropriate reviewers, or let me know how I should make this contribution?

**Comment by nelyahu** [comment]
@tjs-intel - Thanks, we will apply to change the our dev branch, and it will be available on next release.

**Comment by tjs-intel** [comment]
@nelyahu what is the timeline of the next release?

**Comment by tjs-intel** [comment]
I am promised that this will be in the next release

**Pull request closed without merging**
